---
- name: Ensure MC is installed.
  apt: pkg=mc state=installed

- name: Ensure ini dir exist
  file: path="{{ item.dir }}/.config/mc" state=directory recurse=yes
  with_items: "{{ users }}"

- name: Copy ini file template
  template: src=templates/mc.ini.j2 dest="{{ item.dir }}/.config/mc/ini"
  with_items: "{{ users }}"
